### ISSUE TITLE
Issue with RegularTransferLR when sklearn estimator's fit_intecept=False

### ISSUE THREAD

**Issue by ymouad** [adapt-python/adapt#102]
Hi,

It seems that RegularTransferLR does not work with a sklearn model when its fit_intercept==False. See the example bellow.

![image](https://user-images.githubusercontent.com/59994796/234289621-7671ce6e-2344-44e0-861e-2910a263a1fb.png)

**Comment by antoinedemathelin** [comment]
Hi @ymouad,
Thank you for reporting this bug, it should be fixed now

Best,
