### ISSUE TITLE
Save tradaboost model

### ISSUE THREAD

**Issue by 971766904** [adapt-python/adapt#109]
I want to know how to save a model trained by tradaboost whose estimator is LGBMClassifier and how to load a saved model when I need to deploy on real time situation.

**Comment by antoinedemathelin** [comment]
Hi @971766904,

Thank you for your interest in the Adapt library. To save and load the TrAdaBoost model, you can use `joblib` as for scikit-learn estimators.

Here is an example:


```python
import joblib
from adapt.utils import make_classification_da
from adapt.instance_based import TrAdaBoost
from lightgbm import LGBMClassifier

Xs, ys, Xt, yt = make_classification_da()

model = TrAdaBoost(estimator=LGBMClassifier(num_leaves=20))
model.fit(Xs, ys, Xt, yt)

# Save the fitted model
joblib.dump(model, "model.pkl")

# Load the model and make predictions
loaded_model = joblib.load("model.pkl")
loaded_model.predict(Xt)
```

**Comment by 971766904** [comment]
> Hi @971766904,
> 
> Thank you for your interest in the Adapt library. To save and load the TrAdaBoost model, you can use `joblib` as for scikit-learn estimators.
> 
> Here is an example:
> 
> ```python
> import joblib
> from adapt.utils import make_classification_da
> from adapt.instance_based import TrAdaBoost
> from lightgbm import LGBMClassifier
> 
> Xs, ys, Xt, yt = make_classification_da()
> 
> model = TrAdaBoost(estimator=LGBMClassifier(num_leaves=20))
> model.fit(Xs, ys, Xt, yt)
> 
> # Save the fitted model
> joblib.dump(model, "model.pkl")
> 
> # Load the model and make predictions
> loaded_model = joblib.load("model.pkl")
> loaded_model.predict(Xt)
> ```

thank your for your reply
