### ISSUE TITLE
Question on function that provides probability or confidence values for a prediction

### ISSUE THREAD

**Issue by SrikrishnaBhat** [adapt-python/adapt#123]
I had a look at the API reference and must have missed it. I would like to know if adapt has an option to provide probability/confidence values for a prediction similar to scikit-learn's and XGBoost's `predict_proba` function. If not, is it possible to add it?

**Comment by antoinedemathelin** [comment]
Hi @SrikrishnaBhat,
Yes, if you use a sklearn estimator, you can access every methods of the estimator through the `estimator_` attribute. Here is a small example:

```python

import numpy as np
from adapt.instance_based import KMM
from sklearn.linear_model import LogisticRegression

np.random.seed(0)
Xs = np.random.randn(10, 2)
ys = np.random.choice(2, 10)

Xt = np.random.randn(10, 2)

model = KMM(LogisticRegression(), verbose=0)
model.fit(Xs, ys, Xt)

model.estimator_.predict_proba(Xt)

# array([[0.32728159, 0.67271841],
#        [0.46798244, 0.53201756],
#        [0.19779639, 0.80220361],
#        [0.37254084, 0.62745916],
#        [0.41436869, 0.58563131],
#        [0.32523053, 0.67476947],
#        [0.46625157, 0.53374843],
#        [0.48592336, 0.51407664],
#        [0.55101478, 0.44898522],
#        [0.5248281 , 0.4751719 ]])
```

**Comment by SrikrishnaBhat** [comment]
Sorry, I forgot to respond back. This works and answers my question, thanks for the quick reply, I am closing this issue.
