### ISSUE TITLE
issue with ‘TrAdaBoostR2’ ：TypeError: predict() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by 9527-ly** [adapt-python/adapt#53]
When I use the following case code in toy regression

from adapt.instance_based import TrAdaBoostR2
model = TrAdaBoostR2(get_model(), n_estimators=30, random_state=0)
save_preds = SavePrediction()
model.fit(Xs.reshape(-1, 1), ys.reshape(-1, 1), Xt_lab.reshape(-1, 1), yt_lab.reshape(-1, 1)，
callbacks=[save_preds], epochs=100, batch_size=110, verbose=0)

I encountered the following error message：
File "G://adapt-master/test1.py", line 112, in <module>
    model.fit(Xs.reshape(-1, 1), ys.reshape(-1, 1), Xt_lab.reshape(-1, 1), yt_lab.reshape(-1, 1)
  File "G:\adapt-master\adapt\instance_based\_tradaboost.py", line 267, in fit
    **fit_params
  File "G:\adapt-master\adapt\instance_based\_tradaboost.py", line 308, in _boost
    ys_pred = estimator.predict_proba(Xs)
  File "C:\Users\.conda\envs\tgpu\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 283, in predict_proba
    preds = self.predict(x, batch_size, verbose)
TypeError: predict() takes 2 positional arguments but 4 were given

**Comment by antoinedemathelin** [comment]
Hi @9527-ly,
Thank you for reporting the issue. Which version of Tensorflow are you using?
It seems that your tensorflow Model has a "predict_proba" method which is not the case for me?
Best,

**Comment by antoinedemathelin** [comment]
Changes have been made to handle the case of Tensorflow model having a `predict_proba` method (#54)

**Comment by 9527-ly** [comment]
Hi @antoinedemathelin,
Tensorflow_ CPU = 2.6 and Tensorflow_ GPU = 2.4 will encounter this problem. Then, I looked at the source code in _tradaboost.py.

I found the following code：
if hasattr(estimator, "predict_proba"):
            ys_pred = estimator.predict_proba(Xs)
            yt_pred = estimator.predict_proba(Xt)
elif hasattr(estimator, "_predict_proba_lr"):
            ys_pred = estimator._predict_proba_lr(Xs)
            yt_pred = estimator._predict_proba_lr(Xt)

Then， if I delete _proba and _proba_lr and run the code again, the above error will not be reported. I don't know if my modification is reasonable

**Comment by antoinedemathelin** [comment]
Hi @9527-ly ,
Yes, the problem comes from `predict_proba` being called instead of `predict` on a Tensorflow Sequential model.
I made a change in that sense, you can install the current stable version of the library with the command:

`pip install git+https://github.com/adapt-python/adapt.git`

Please tell me if you still have the issue.
Best,

**Comment by 9527-ly** [comment]
Hi @antoinedemathelin,
Thanks a lot. 

At the same time, I would also like to ask you a few questions. I would be grateful if I could get your reply. I found that some examples and even some domain adaptive methods can only operate in the two-dimensional FC model. For example, if I replace the default encoder and task network with a custom 1D-CNN in the DeepCORAL. I will get the following error:
File "G:\adapt-master\adapt\base.py", line 1338, in call
    return self.task_(x)
G:\adapt-master\adapt\feature_based\_deepcoral.py:137 train_step
        ys_pred = self.task_(Xs_enc, training=True)
Input 0 of layer task is incompatible with the layer:  expected min_ndim=3, found ndim=2. Full shape received: (1, 10)

Then, I looked at the source code in _deepcoral.py and base.py. I found that the following code caused the error：
def call(self, inputs):
        x = self.encoder_(inputs)
        return self.task_(x)

Xs_enc = self.encoder_(Xs, training=True)
ys_pred = self.task_(Xs_enc, training=True)

So I modified them as follows：
def call(self, inputs):
        x = self.encoder_(inputs)
        x = tf.expand_dims(x, -1)
        return self.task_(x)

Xs_enc = self.encoder_(Xs, training=True)
Xs_enc=tf.expand_dims(Xs_enc,-1)
ys_pred = self.task_(Xs_enc, training=True)


I don't know if my modification is reasonable. In the MDD method, I also modify it in this way.  At the same time, I may test on some more complex models later, such as 2d-cnn, convlstm, etc. This question has always puzzled me. Look forward to your reply.
Best,

**Comment by antoinedemathelin** [comment]
Hi @9527-ly ,
For what I have seen in the litterature, people mainly use FC model for the task and Conv for the encoder.
Thus, if a `Flatten` layer is put at the end of the encoder, the  input shape of the task network is of dimension 2.

Thank you for reporting your needs of using an encoded space of higher dimension. I see that your proposed solution is to put an `expand_dim` before the task. Did you try to put a `Reshape` layer at the beggining of the task network to make this expand_dim ? In your case the task network has convolution layers right ?
