### ISSUE TITLE
Inputs as generators to adapt.parameter_based.RegularTransferLR

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [adapt-python/adapt#57]
The inputs to different implementations eg: finetuning or RegularTransferLR is numpy arrays of source and target data. Can we give generator instead?

**Comment by antoinedemathelin** [comment]
Hello @sreenivasaupadhyaya,
Yes of course, tensorflow dataset from generators can be given instead.
You can look at this example with `FineTuning` to see how to use generators: https://adapt-python.github.io/adapt/examples/Flowers_example.html
I hope it will help you,
Best,

**Comment by sreenivasaupadhyaya** [comment]
@antoinedemathelin , thanks for the quick reply.
Even the description for https://adapt-python.github.io/adapt/generated/adapt.parameter_based.RegularTransferNN.html) shows that Xs should be a numpy array. 

In my application, the data size is large and is only possible to load it in batches using the data generators provided by tensorflow/keras framework. So My question was that, if the adapt framework in general compatible with the input being generators rather than the array itself.

**Comment by sreenivasaupadhyaya** [comment]
Hi @antoinedemathelin , 

Thanks for your feedback.
I am trying to  enable a simple training setup for the DANN using data generators and i encounter some error which looks like related to the mis match between the expected input and what  my generator provides.

my generator provides tuples (input output pair) of sizes : "((128, 10, 300, 64), (128, 60, 7))" where the batch size is 128 and the input shape of each sample is 10 channels of 300x64 and output is 60,7. This is for the source data generator.

For target data i have a generator to give only the input part.

code
`#inititalize the DANN
model_dann = adapt.feature_based.DANN(encoder=get_model_encode(), task=get_model_task(), discriminator=get_model_descriminator(), Xt=data_gen_target.generate(),
             loss="categorical_crossentropy", optimizer=Adam(0.001),
            copy=True, lambda_=1., metrics=["acc"], gamma=10., random_state=0, verbose=10)


#train DANN
model_dann.fit_generator(generator=data_gen_source)`


Error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-70-4ae1e5438f33> in <module>
----> 1 model_dann.fit_generator(generator=data_gen_train)
      2 

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1987         use_multiprocessing=use_multiprocessing,
   1988         shuffle=shuffle,
-> 1989         initial_epoch=initial_epoch)
   1990 
   1991   @doc_controls.do_not_generate_docs

/usr/local/lib/python3.6/dist-packages/adapt-0.4.1-py3.6.egg/adapt/base.py in fit(self, X, y, Xt, yt, domains, **fit_params)
    970         ### 2.1 Source
    971         if not isinstance(X, tf.data.Dataset):
--> 972             check_arrays(X, y)
    973             if len(y.shape) <= 1:
    974                 y = y.reshape(-1, 1)

/usr/local/lib/python3.6/dist-packages/adapt-0.4.1-py3.6.egg/adapt/utils.py in check_arrays(X, y, **kwargs)
    131     X, y
    132     """    
--> 133     X = check_array(X, ensure_2d=True, allow_nd=True, **kwargs)
    134     y = check_array(y, ensure_2d=False, allow_nd=True, dtype=None, **kwargs)
    135     if X.shape[0] != y.shape[0]:

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    689                     "Reshape your data either using array.reshape(-1, 1) if "
    690                     "your data has a single feature or array.reshape(1, -1) "
--> 691                     "if it contains a single sample.".format(array))
    692             # If input is 1D raise error
    693             if array.ndim == 1:

ValueError: Expected 2D array, got scalar array instead:
array=<cls_data_generator.DataGenerator object at 0x7fc6757849b0>.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.`

**Comment by antoinedemathelin** [comment]
Hi  @sreenivasaupadhyaya,

Thank you for the feedback. I understand your problem. `DANN` object has not the `fit_generator` method implemented yet, however you can give generated data in the `fit` method through the objects `tf.data.Dataset.from_generator`.

Here is an example that should run and do what you want to do:

```
import adapt
import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import SGD

# Fake data for the example
X_target = np.random.randn(3, 128, 10, 300, 64)
X_source = np.random.randn(3, 128, 10, 300, 64)
y_source = np.random.randn(3, 128, 60, 7)

nb_of_target_data = 3
nb_of_source_data = 3

# Fake networks
def get_model_encoder():
    mod = tf.keras.Sequential()
    mod.add(tf.keras.layers.GlobalAvgPool3D(input_shape=(128, 10, 300, 64)))
    return mod

def get_model_task():
    mod = tf.keras.Sequential()
    mod.add(tf.keras.layers.Dense(1, input_shape=(64,)))
    mod.add(tf.keras.layers.Dense(128*60*7))
    mod.add(tf.keras.layers.Reshape((128, 60, 7)))
    return mod

def get_model_discriminator():
    mod = tf.keras.Sequential()
    mod.add(tf.keras.layers.Dense(1, activation="sigmoid"))
    return mod


# Build your generators by yielding the data
def data_gen_target():
    for i in range(nb_of_target_data):
        yield X_target[i] # data of shape (128, 10, 300, 64)
        
def data_gen_source():
    for i in range(nb_of_source_data):
        yield (X_source[i], y_source[i]) # tuple of shape ((128, 10, 300, 64), (128, 60, 7))
        

# Build tensorflow datasets
target_data = tf.data.Dataset.from_generator(data_gen_target,
                                             output_types=tf.float32,
                                             output_shapes=[128, 10, 300, 64])

source_data = tf.data.Dataset.from_generator(data_gen_source,
                                        output_types=(tf.float32, tf.float32),
                                        output_shapes=([128, 10, 300, 64], [128, 60, 7]))

# inititalize the DANN
model_dann = adapt.feature_based.DANN(encoder=get_model_encoder(),
                                      task=get_model_task(),
                                      discriminator=get_model_descriminator(),
                                      Xt=target_data,
                                      loss="mse",
                                      optimizer=SGD(0.01),
                                      copy=True,
                                      lambda_=tf.Variable(1.),
                                      random_state=0,
                                      verbose=1)

# train DANN
model_dann.fit(source_data,
               epochs=3,
               batch_size=1,
               callbacks=[adapt.utils.UpdateLambda(lambda_max=1., gamma=10.)])
```

Of course you don't have access to `X_target` and `X_source` as they are too big to enter in RAM, what you should change here is the `data_gen_target` and `data_gen_source` functions. In these functions you can create a loop over the file names of your data, at each step you load one data and yield it.

You can give your own network architecture, but be careful that all shapes match.

You can see that I changed some settings in your code:
-  First the `gamma` should now be given to a callbacks called `UpdateLambda` that does the update of `lambda` at each step presented in the DANN paper. We forgot to remove the parameter from the `DANN` object.
- I also changed the loss, you give the categorical crossentropy but I am not sure you really want to use it? Indeed, the shape of your output is a 3D tensor, it's not very common to use the categorical crossentropy on this kind of outputs... I put the mean_squared_error "mse" instead.
- Finally, I used the `SGD` optimizer instead of `Adam`, `Adam` is working but, from my experience, it often produces instable results with DANN.

Please do not hesitate if you have other questions or if you encounter some bugs. Your feedbacks are precious!

Best,

**Comment by sreenivasaupadhyaya** [comment]
Thanks @antoinedemathelin  I am already testing it.

**Comment by sreenivasaupadhyaya** [comment]
@antoinedemathelin Thanks for the advise. I am progressed with this but I am bit stuck at a point where my code fails with Adapt. I am wondering if this expected in the way Adapt framework is designed.

The below is the description of my setup, The models look like this

**Model Encoder**
Learning rate used is  0.001
Model: "functional_89"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_91 (InputLayer)        [(None, 10, 300, 64)]     0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 16, 300, 64)       1456      
_________________________________________________________________
batch_normalization_17 (Batc (None, 16, 300, 64)       256       
_________________________________________________________________
activation_17 (Activation)   (None, 16, 300, 64)       0         
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 16, 60, 16)        0         
_________________________________________________________________
dropout_15 (Dropout)         (None, 16, 60, 16)        0         
_________________________________________________________________
permute_15 (Permute)         (None, 60, 16, 16)        0         
_________________________________________________________________
reshape_15 (Reshape)         (None, 60, 256)           0         
=================================================================
Total params: 1,712
Trainable params: 1,584
Non-trainable params: 128

**Model Task**
_________________________________________________________________
Model: "functional_91"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_92 (InputLayer)        [(None, 60, 256)]         0         
_________________________________________________________________
time_distributed_50 (TimeDis (None, 60, 128)           32896     
_________________________________________________________________
time_distributed_51 (TimeDis (None, 60, 7)             903       
=================================================================
Total params: 33,799
Trainable params: 33,799
Non-trainable params: 0

**Model descriminator**
_________________________________________________________________
Model: "functional_93"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_93 (InputLayer)        [(None, 60, 256)]         0         
_________________________________________________________________
time_distributed_52 (TimeDis (None, 60, 128)           32896     
_________________________________________________________________
time_distributed_53 (TimeDis (None, 60, 1)             129       
=================================================================
Total params: 33,025
Trainable params: 33,025
Non-trainable params: 0


`from tensorflow.keras.layers import MaxPooling2D,Activation,TimeDistributed, BatchNormalization, Dense,Input, Conv2D, Reshape, Permute, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Model

#create a tf model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
# Neural network
def get_model_encode():
    # model definition
    spec_start = Input(shape=(10,300,64))
    # CNN
    spec_cnn = spec_start
    conv_layers = 1
    nb_cnn2d_filt = [16]
    for i in range(conv_layers):
        spec_cnn = Conv2D(filters=nb_cnn2d_filt[i], kernel_size=(3, 3), padding='same')(spec_cnn)
        spec_cnn = BatchNormalization()(spec_cnn)
        spec_cnn = Activation('relu')(spec_cnn)
        spec_cnn = MaxPooling2D(pool_size=(5, 4),data_format='channels_first', padding='same')(spec_cnn)
        spec_cnn = Dropout(0.05)(spec_cnn)
    spec_cnn = Permute((2, 1, 3))(spec_cnn)

    #Reshape
    spec_rnn = Reshape((60,-1 ))(spec_cnn)
    sed = spec_rnn

    model = Model(inputs=spec_start, outputs=sed)
    print('Learning rate used is ', 0.001)

    model.compile(optimizer='adam', loss= 'categorical_crossentropy',metrics=['accuracy','categorical_crossentropy'])#,sample_weight_mode="temporal"
    #['categorical_crossentropy',weightedLoss()]
    model.summary()
    return model

def get_model_task():
    spec_start = Input(shape=(60,256))
    task_out = TimeDistributed(Dense(128, input_dim=256, activation='relu'))(spec_start)
    task_out = TimeDistributed(Dense(7, activation='softmax'))(task_out)
    
    model_task = Model(inputs=spec_start, outputs=task_out)
    
    model_task.compile(optimizer='adam', loss='categorical_crossentropy')
    model_task.summary()
    return model_task
def get_model_descriminator():

    
    spec_start = Input(shape=(60,256))
    task_out = TimeDistributed(Dense(128, input_dim=256, activation='relu'))(spec_start)
    task_out = TimeDistributed(Dense(1, activation='sigmoid'))(task_out)
    
    model_descriminator = Model(inputs=spec_start, outputs=task_out)
    
    
    model_descriminator.compile(optimizer='adam', loss='binary_crossentropy')
    model_descriminator.summary()
    return model_descriminator
`

My source data generator returns input data and labels of size (128, 10, 300, 64)  and (128, 60, 7)  respectively with 128 being the batch size, 10 is the input channels (channel first format). To put it simply, for each 10x300x64 input data point ( channel x time_frames x input_features) output is of size 60 x7 (time frame x dimension).

Issue: 

`---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-71-40dcda9a8e7b> in <module>
      5 
      6 #train DANN
----> 7 model_dann.fit(X=data_source, epochs=1)
      8 

/usr/local/lib/python3.6/dist-packages/adapt/base.py in fit(self, X, y, Xt, yt, domains, **fit_params)
   1038             else:
   1039                 shape = Xt.shape[1:]
-> 1040             self._initialize_weights(shape)
   1041 
   1042 

/usr/local/lib/python3.6/dist-packages/adapt/base.py in _initialize_weights(self, shape_X)
   1586 
   1587     def _initialize_weights(self, shape_X):
-> 1588         self(np.zeros((1,) + shape_X))
   1589         if hasattr(self, "encoder_"):
   1590             X_enc = self.encoder_(np.zeros((1,) + shape_X))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    983 
    984         with ops.enable_auto_cast_variables(self._compute_dtype_object):
--> 985           outputs = call_fn(inputs, *args, **kwargs)
    986 
    987         if self._activity_regularizer:

/usr/local/lib/python3.6/dist-packages/adapt/base.py in call(self, inputs)
   1333 
   1334     def call(self, inputs):
-> 1335         x = self.encoder_(inputs)
   1336         return self.task_(x)
   1337 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    983 
    984         with ops.enable_auto_cast_variables(self._compute_dtype_object):
--> 985           outputs = call_fn(inputs, *args, **kwargs)
    986 
    987         if self._activity_regularizer:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in call(self, inputs, training, mask)
    384     """
    385     return self._run_internal_graph(
--> 386         inputs, training=training, mask=mask)
    387 
    388   def compute_output_shape(self, input_shape):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in _run_internal_graph(self, inputs, training, mask)
    506 
    507         args, kwargs = node.map_arguments(tensor_dict)
--> 508         outputs = node.layer(*args, **kwargs)
    509 
    510         # Update tensor_dict.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    983 
    984         with ops.enable_auto_cast_variables(self._compute_dtype_object):
--> 985           outputs = call_fn(inputs, *args, **kwargs)
    986 
    987         if self._activity_regularizer:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/pooling.py in call(self, inputs)
    294         strides=strides,
    295         padding=self.padding.upper(),
--> 296         data_format=conv_utils.convert_data_format(self.data_format, 4))
    297     return outputs
    298 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py in max_pool(value, ksize, strides, padding, data_format, name, input)
   4518         padding=padding,
   4519         data_format=data_format,
-> 4520         name=name)
   4521 
   4522 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py in max_pool(input, ksize, strides, padding, data_format, name)
   5241       return _result
   5242     except _core._NotOkStatusException as e:
-> 5243       _ops.raise_from_not_ok_status(e, name)
   5244     except _core._FallbackException:
   5245       pass

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6841   message = e.message + (" name: " + name if name is not None else "")
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access
   6845 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: tensor_in_shape must have 2 spatial dimensions. 5 1 [Op:MaxPool]`


Question: Thought it suggests it comes from the max pooling layer used, Could it be because of the using Time distributed layers in the models and that some how has some compatibility issues with adapt?

**Comment by sreenivasaupadhyaya** [comment]
@antoinedemathelin  any recommendation for method to save the adapt models and load it back. Since they are sub classed models, the normal methods dont work as expected.

for eg: normal model.save doesnt work. I also tried other method as seen in the screen shot
![Screenshot 2022-07-15 at 14 38 40](https://user-images.githubusercontent.com/7950974/179224750-d17c533a-2703-46d6-b2e0-40c57e914f39.png)

**Comment by antoinedemathelin** [comment]
Hi @sreenivasaupadhyaya,
Yes you can call the `save_weights` method with `save_format = 'h5'`.

Example:
```python
model_DANN.save_weights("dann.h5", save_format = 'h5')
``` 

To load the weights later, what you can do is to instantiate a new model and fit with `epochs=0` to build the architecture, and then use `load_weights`:

```python
new_model_dann = adapt.feature_based.DANN(encoder=get_model_encoder(),
                                      task=get_model_task(),
                                      discriminator=get_model_descriminator(),
                                      Xt=target_data)

new_model_dann.fit(source_data, epochs=0, batch_size=1)
new_model_dann.load_weights("dann.h5")
```

**Comment by sreenivasaupadhyaya** [comment]
> Hi @sreenivasaupadhyaya, Yes you can call the `save_weights` method with `save_format = 'h5'`.
> 
> Example:
> 
> ```python
> model_DANN.save_weights("dann.h5", save_format = 'h5')
> ```
> 
> To load the weights later, what you can do is to instantiate a new model and fit with `epochs=0` to build the architecture, and then use `load_weights`:
> 
> ```python
> new_model_dann = adapt.feature_based.DANN(encoder=get_model_encoder(),
>                                       task=get_model_task(),
>                                       discriminator=get_model_descriminator(),
>                                       Xt=target_data)
> 
> new_model_dann.fit(source_data, epochs=0, batch_size=1)
> new_model_dann.load_weights("dann.h5")
> ```

I used it this way now. Thanks for the reply.
Closing this issue.
