### ISSUE TITLE
FA multi-source example

### ISSUE THREAD

**Issue by davidshumway** [adapt-python/adapt#86]
Is there an example of using FA in the multi-source context? Going off of the documentation, I thought the following should work but it's failing:

> FA can be used for multi-source DA by giving list of source data for arguments Xs, ys of fit method : Xs = [Xs1, Xs2, …], ys = [ys1, ys2, …]

```python
Xs1, Xs2, Xs3 = pd.DataFrame(...), pd.DataFrame(...), pd.DataFrame(...)
ys1, ys2, ys3 = [...], [...], [...]
Xss = [
  Xs1,
  Xs2,
  Xs3,
]
yss = [
  ys1,
  ys2,
  ys3
]
model.fit(Xss, yss)
```

i.e. Xs1-3 are Pandas dataframes containing source features and yss1-3 are each a list of observed values.

But the output is: `ValueError: Expected 2D array, got 1D array instead: [contents of Xss]`

**Comment by antoinedemathelin** [comment]
Hi @davidshumway,
Sorry, the documentation has not been updated yet. If you want to use FA in the multi-source setting, you should use the `domains` argument:

```python
import numpy as np
from adapt.feature_based import FA

Xs1 = np.random.randn(10, 3)
Xs2 = np.random.randn(20, 3)
Xt = np.random.randn(5, 3)

ys1 = np.random.randn(10)
ys2 = np.random.randn(20)
yt = np.random.randn(5)

domains = [0]*len(Xs1) + [1]*len(Xs2)

Xss = np.concatenate((Xs1, Xs2))
yss = np.concatenate((ys1, ys2))

fa = FA(Xt=Xt, yt=yt)
fa.fit(Xss, yss, domains=domains);

"""
Fit transform...
Previous shape: (30, 3)
New shape: (35, 12)
Fit Estimator...
"""

```

**Comment by davidshumway** [comment]
Thanks for the clarification, @antoinedemathelin!
