### ISSUE TITLE
Using models with GridSearchCV causes unnecessary ("getting") print statements

### ISSUE THREAD

**Issue by davidshumway** [adapt-python/adapt#87]
Using models with GridSearchCV is causing unnecessary ("getting") print statements.

```python
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor

param_grid = {
  'estimator': [RandomForestRegressor(), MLPRegressor()],
  'lambda_': [1e-1, 1e-5, 1e-9]
} 
gsc = GridSearchCV(CORAL(Xt=Xt, random_state=0, verbose=0),
  param_grid, cv=2, scoring='neg_mean_squared_error',
  n_jobs=-1)
```

Example output:
> getting
 getting
 getting
 getting
 getting
 getting
 getting

ADAPT Version: 0.4.2

The statement appears to be from here: https://github.com/adapt-python/adapt/blob/b390ac6a443395688ae12faf463432b6d8ce233f/adapt/base.py#L798

**Comment by antoinedemathelin** [comment]
Hi @davidshumway,
Thank you for noticing this bug, we patch this asap!
Best,

**Comment by davidshumway** [comment]
Thanks, @antoinedemathelin!
