### ISSUE TITLE
FA (Frustratingly easy domain adaptation) for multi domain

### ISSUE THREAD

**Issue by treena908** [adapt-python/adapt#93]
For multi domain FA, the code doesn't work. For the attached code of two domain, it throws following error:
 
 File "/AD-HOME/sfarza3/Research/DA_detection_AD/code/venv/lib/python3.8/site-p
ackages/adapt/feature_based/_fa.py", line 162, in fit_transform                 
    Xs_emb_i = np.concatenate(                                                  
  File "<__array_function__ internals>", line 5, in concatenate                 
ValueError: all the input arrays must have same number of dimensions, but the ar
ray at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)  

![multi](https://user-images.githubusercontent.com/36607788/210288056-2c63b067-8513-480f-9cd4-bc5006acd9f4.jpg)

**Comment by antoinedemathelin** [comment]
Hi @treena908,
Sorry, the Note in FA has still not be updated, although the problem has already been reported #86 
Please look at #86 to see an example of multisource with FA.
Best,
