### ISSUE TITLE
How to save model weights after transfer learning

### ISSUE THREAD

**Issue by 9527-ly** [adapt-python/adapt#94]
How to save the adjusted model after updating the model weight using domain adaptation or transfer learning? For example, I used the TrAdaBoostR2 method. But when I save the model, whether it is model.save or model.save_ weights have no effect.

**Comment by 9527-ly** [comment]
![image](https://user-images.githubusercontent.com/71538270/216758310-d65bd79c-f871-405b-b3bc-17c2babc5f38.png)

**Comment by antoinedemathelin** [comment]
Hi @9527-ly,
Thank you for your interest in the adapt library.
TrAdaBoostR2 has no `save_weights` method. However, you may succeed to pickle the object using `joblib`:

```python
import joblib

joblib.dump(model, "model.pkl")

loaded_model = joblib.load("model.pkl")
```

If for some reason it doesn't work, you can always save the weights of every estimator in TrAdaBoostR2:

```python

for i in range(model.n_estimators):
    model.estimators_[i].save_weights("model_%i.hdf5"%i)
```

Please, do not hesitate if you have further questions.

Best,

**Comment by 9527-ly** [comment]
> 

Thank you for your answer. I have succeeded to pickle the object using joblib
