### ISSUE TITLE
DANN with multiclass problems

### ISSUE THREAD

**Issue by andreapi87** [adapt-python/adapt#97]
It seems that the implemented DANN class does not work with multiclass, also if I provide a custom task network having as last layer Dense(n_classes, activation='softmax').

**Comment by antoinedemathelin** [comment]
Hi @andreapi87,
Thank you for your interest in the ADAPT library!
What do you mean exactly by "it does not work"? What is the error message you get?
Can you please post the whole code you used to help us identify the problem?
Best,
